sudo: false
language: node_js
node_js:
- '6.0'
#cache:
#  directories:
#  - node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- npm install bit-bin --global
- bit install
- npm install
script:
- npm run --silent build
after_success:
- bash deploy.sh
